[project]
name = "hyper-treasury"
authors = ["HyperTreasury Team"]
description = "A secure, flexible treasury management system on the Stacks blockchain"
telemetry = false
requirements = []
[contracts.treasury-vault]
path = "contracts/treasury-vault.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
